  @Test
  public void testName() throws Exception {
    CompletableFuture<MessageActionItem> future = new CompletableFuture<>();
    when(transmitter.sendShowMessageRequest(any())).thenReturn(future);

    ServerInitializerImpl initializer = new ServerInitializerImpl();
    CheLanguageClient client = new CheLanguageClient(eventService, transmitter, "id");
    CompletableFuture<Pair<LanguageServer, InitializeResult>> initialize =
        initializer.initialize(launcher, client, "/tmp");
    Pair<LanguageServer, InitializeResult> resultPair = initialize.get();
    server = resultPair.first;
    ArgumentCaptor<ShowMessageRequestParams> captor =
        ArgumentCaptor.forClass(ShowMessageRequestParams.class);
    verify(transmitter, timeout(1500)).sendShowMessageRequest(captor.capture());

    ShowMessageRequestParams value = captor.getValue();
    assertNotNull(value);
    assertEquals(value.getType(), MessageType.Error);
    assertEquals(value.getMessage(), "Error Message!!!!");
  }

