  @Test
  public void testFail2() throws Exception {
    consoles.closeProcessesArea();
    projectExplorer.scrollToItemByPath(PROJECT_NAME + "/src/main/webapp");
    setFieldsForTest("testfail2");
    projectExplorer.openItemByPath(pathToCurrentPackage + "/A.java");
    editor.waitActiveEditor();
    editor.waitTextIntoEditor(contentFromInA);
    editor.setCursorToDefinedLineAndChar(14, 23);
    editor.launchRefactorFormFromEditor();
    editor.launchRefactorFormFromEditor();
    refactor.waitRenameParametersFormIsOpen();
    refactor.waitUpdateReferencesIsSelected();
    refactor.typeAndWaitNewName("i");
    refactor.clickOkButtonRefactorForm();
    askDialog.acceptDialogWithText("Duplicate parameter i");
    refactor.waitRenameParametersFormIsClosed();
    editor.closeFileByNameWithSaving("A");
  }

