    @Test
    public void testOnPushClickedWhenPushWSRequestIsFailed() throws Exception {
        presenter.showDialog();
        presenter.onPushClicked();

        verify(service).push(anyString(), anyObject(), anyListOf(String.class), anyString(), anyBoolean(),
                             asyncCallbackVoidCaptor.capture());
        AsyncRequestCallback<PushResponse> voidCallback = asyncCallbackVoidCaptor.getValue();
        Method onFailure = GwtReflectionUtils.getMethod(voidCallback.getClass(), "onFailure");
        onFailure.invoke(voidCallback, mock(Throwable.class));

        verify(service).push(anyString(), eq(rootProjectConfig), anyListOf(String.class), eq(REPOSITORY_NAME), eq(DISABLE_CHECK),
                             (AsyncRequestCallback<PushResponse>)anyObject());
        verify(view).close();
        verify(constant, times(2)).pushFail();
        verify(gitOutputConsoleFactory).create(PUSH_COMMAND_NAME);
        verify(console).printError(anyString());
        verify(consolesPanelPresenter).addCommandOutput(anyString(), eq(console));
        verify(notificationManager).notify(anyString(), rootProjectConfig);
    }

