    @Test
	public void test47() throws Exception {
		helper2("A", "B");
	}

