  @Test
  public void testFail9() throws Exception {
    helper1_0("y", "e", "getE", true, true);
  }

