  @Test
  public void testResume() throws Exception {
    ResumeActionDto resumeAction = mock(ResumeActionDto.class);

    doReturn(promiseVoid).when(service).resume(SESSION_ID, resumeAction);
    doReturn(resumeAction).when(dtoFactory).createDto(ResumeActionDto.class);

    debugger.resume();

    verify(observer).onPreResume();

    verify(promiseVoid).catchError(operationPromiseErrorCaptor.capture());
    operationPromiseErrorCaptor.getValue().apply(promiseError);
    verify(promiseError).getCause();

    assertTrue(debugger.isConnected());
  }

