    private Operation<PromiseError> getUserErrorOp(final WorkflowExecutor executor, final Context context) {
        return new Operation<PromiseError>() {
            @Override
            public void apply(PromiseError error) throws OperationException {
                try {
                    throw error.getCause();
                } catch (UnauthorizedException unEx) {
                    authenticate(executor, context);
                } catch (Throwable thr) {
                    handleThrowable(thr, executor, context);
                }
            }
        };
    }

